name: DotnetSixProjectBuilder
on:
  push:
    branches: [ feature/get-user ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.7.21379.14
        
     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # CustomerSet.Find.InOut.csproj
    
    - name: Restore CustomerSet.Find.InOut.csproj
      run: dotnet restore ./src/*/*/CustomerSet.Find.InOut.csproj

    - name: Build CustomerSet.Find.InOut.csproj
      run: dotnet build ./src/*/*/CustomerSet.Find.InOut.csproj --no-restore  -c Release

    - name: Pack CustomerSet.Find.InOut.csproj
      run: dotnet pack ./src/*/*/CustomerSet.Find.InOut.csproj --no-restore -o ~/nuget  -c Release

    # CustomerSet.Find.Api.csproj
    
    - name: Restore CustomerSet.Find.Api.csproj
      run: dotnet restore ./src/*/*/CustomerSet.Find.Api.csproj

    - name: Build CustomerSet.Find.Api.csproj
      run: dotnet build ./src/*/*/CustomerSet.Find.Api.csproj --no-restore  -c Release

    - name: Pack CustomerSet.Find.Api.csproj
      run: dotnet pack ./src/*/*/CustomerSet.Find.Api.csproj --no-restore -o ~/nuget  -c Release

    # Incident.Create.InOut.csproj
    
    - name: Restore Incident.Create.InOut.csproj
      run: dotnet restore ./src/*/*/Incident.Create.InOut.csproj

    - name: Build Incident.Create.InOut.csproj
      run: dotnet build ./src/*/*/Incident.Create.InOut.csproj --no-restore  -c Release

    - name: Pack Incident.Create.InOut.csproj
      run: dotnet pack ./src/*/*/Incident.Create.InOut.csproj --no-restore -o ~/nuget  -c Release

    # Incident.Create.Api.csproj
    
    - name: Restore Incident.Create.Api.csproj
      run: dotnet restore ./src/*/*/Incident.Create.Api.csproj

    - name: Build Incident.Create.Api.csproj
      run: dotnet build ./src/*/*/Incident.Create.Api.csproj --no-restore  -c Release

    - name: Pack Incident.Create.Api.csproj
      run: dotnet pack ./src/*/*/Incident.Create.Api.csproj --no-restore -o ~/nuget  -c Release

    # User.Get.InOut.csproj
    
    - name: Restore User.Get.InOut.csproj
      run: dotnet restore ./src/*/*/User.Get.InOut.csproj

    - name: Build User.Get.InOut.csproj
      run: dotnet build ./src/*/*/User.Get.InOut.csproj --no-restore  -c Release

    - name: Pack User.Get.InOut.csproj
      run: dotnet pack ./src/*/*/User.Get.InOut.csproj --no-restore -o ~/nuget  -c Release
    
    # Shows github vars
    
    - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
    
    # Push
      
    - name: Push Packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
